
CREATE TABLE dws_news_dtl_di(
      id                  string      comment '新闻 id'
    , title               string      comment '标题'
    , sub_title           string      comment '子标题'
    , url                 string      comment '链接'
    , host                string      comment '域名'
    , website             string      comment '网站 id'
    , category_text       string      comment '分类/频道原始文本'
    , category            string      comment '分类/频道 id'
    , location            string      comment '地点'
    , ctry_iso_cd         string      comment '国家编码'
    , language            string      comment '语言'
    , author_id           string      comment '作者 id'
    , author_name         list[author]comment '作者名称'
    , author_information  map         comment '作者信息'
    , author_url          string      comment '作者链接'
    , publish_time        string      comment '发布时间'
    , description         string      comment '简介'
    , content             string      comment '正文'
    , image               list[string]comment '图片链接'
    , video               list[string]comment '视频链接'
    , link                list[string]comment '其他链接'
    , view_count          int         comment '浏览数'
    , like_count          int         comment '点赞数'
    , comment_count       int         comment '评论数'
    , repost_count        int         comment '转发数'
    , dislike_count       int         comment '踩数'
    , favorite_count      int         comment '收藏数'
    , tag                 list[string]      comment '标签'
    , keyword             string      comment '关键词/主题'
    , crawl_time          string      comment '数据采集时间,{YYYY-MM-DD HH:mm:ss 东八区时区}'
    , crawl_timestamp     bigint      comment '数据采集时间戳 { 10位 秒级 }'
    , stored_time         string      comment '数据入库时间,{YYYY-MM-DD HH:mm:ss  东八区时区}'
    , stored_timestamp    bigint      comment '数据入库时间戳 { 10位 秒级 }'
) comment '新闻明细表'
  partitioned by (dt string comment '采集日期')
  stored as parquet
;

CREATE TABLE dws_tt_expert_dtl_di(
      id                          string    comment '专家 id'
    , name                        string    comment '专家名'
    , title                       string    comment '专家头衔'
    , url                         string    comment '链接'
    , host                        string    comment '域名'
    , website                     string    comment '网站 id'
    , category_text               string    comment '分类/频道原始文本'
    , category                    string    comment '分类/频道 id'
    , type                        string    comment '类型'
    , location                    string    comment '专家所在地'
    , location_ctry_iso_cd        string    comment '所在地国家编码'
    , nationality_ctry_iso_cd     string    comment '国籍编码'
    , language                    string    comment '语言'
    , description                 string    comment '专家简介'
    , area                        string    comment '专家领域'
    , image                       string    comment '图片链接'
    , phone                       string    comment '联系电话'
    , email                       string    comment '联系邮箱'
    , education                   string    comment '教育背景'
    , twitter_user_id             string    comment '推特账号'
    , linkedin_user_id            string    comment '领英账号'
    , facebook_user_id            string    comment '脸书账号'
    , instagram_user_id           string    comment '照片墙账号'
    , wikipedia_url               string    comment '维基百科链接'
    , expert_website              string    comment '专家个人主页'
    , type                        string    comment '类型'
    , keyword                     string    comment '关键词/主题'
    , associated_program          string    comment '研究项目'
    , crawl_time                  string    comment '数据采集时间,{YYYY-MM-DD HH:mm:ss 东八区时区}'
    , crawl_timestamp             bigint    comment '数据采集时间戳 { 10位 秒级 }'
    , stored_time                 string    comment '数据入库时间,{YYYY-MM-DD HH:mm:ss  东八区时区}'
    , stored_timestamp            bigint    comment '数据入库时间戳 { 10位 秒级 }'
) comment '智库专家明细表'
  partitioned by (dt string comment '采集日期')
  stored as parquet
;

CREATE TABLE dws_tt_report_dtl_di(
      id                  string    comment '智库报告 id'
    , title               string    comment '标题'
    , sub_title           string    comment '子标题'
    , url                 string    comment '链接'
    , host                string    comment '域名'
    , website             string    comment '网站 id'
    , category_text       string    comment '分类/频道原始文本'
    , category            string    comment '分类/频道 id'
    , ctry_iso_cd         string    comment '国家编码'
    , language            string    comment '语言'
    , author_id           string    comment '作者 id'
    , author_name         string    comment '作者名称'
    , author_url          string    comment '作者链接'
    , publish_time        string    comment '发布时间'
    , description         string    comment '描述/摘要'
    , content             string    comment '内容'
    , image               string    comment '图片链接'
    , video               string    comment '视频链接'
    , audio               string    comment '音频链接'
    , file                string    comment '附件链接(文件下载)'
    , link                string    comment '其他链接'
    , view_count          int       comment '浏览数'
    , comment_count       int       comment '评论数'
    , reference           string    comment '参数文献'
    , tag                 string    comment '标签'
    , keyword             string    comment '关键词/主题'
    , footnote            string    comment '脚注'
    , mention_country     string    comment '提及国家'
    , crawl_time          string    comment '数据采集时间,{YYYY-MM-DD HH:mm:ss 东八区时区}'
    , crawl_timestamp     bigint    comment '数据采集时间戳 { 10位 秒级 }'
    , stored_time         string    comment '数据入库时间,{YYYY-MM-DD HH:mm:ss  东八区时区}'
    , stored_timestamp    bigint    comment '数据入库时间戳 { 10位 秒级 }'
) comment '智库报告明细表'
  partitioned by (dt string comment '采集日期')
  stored as parquet
;
